### ISSUE TITLE
Feature: running dashpit in docker

### ISSUE THREAD

**Issue by discipolo** [discipolo/dashpit#1]
**Feature**: spin up dashpit in docker
In order to see a list of links in a webbrowser
as a developer
i want to run a command in my clone to visit the dashpit in my webbrowser

**Scenario**: clone repo and run docker command
Given i have a working docker environment:
When i clone the repo 
And enter the clone
And run the command "docker run -d -P 8080:80 -v $(pwd):/data php:5-apache"
When i open my browser to localhost:80
Then i should see the example links

**Comment by JKrag** [comment]
The issue description should probably mention something about the YAML file with links and titles that we discussed, and at least a general description of the files format. 

In principle, it should be a yaml list of urls and titles, maybe something like:

```
- 
  url: https://www.trello.com/bla-de-bla
  title: Bla De Bla team Trello
-
  url: http://xkcd.com/
  title: procrastination
```

**Comment by discipolo** [comment]
i will probably require you to run composer install to get all the dependencies because i dont want to use pecl or write parsers that already exist.

**Comment by JKrag** [comment]
Is this merged to master?

**Comment by JKrag** [comment]
I added some documentation related to how I got this up and running to test it.
